modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hexparse"
version = "${version}"
displayName = "HexParse"
authors = "YukkuriC"
description = '''
parse pattern registry name code into list iota, and vice versa
'''
#logoFile = ""

[[dependencies.hexparse]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexparse]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hexparse]]
modId = "hexcasting"
mandatory = true
versionRange = "[0,)"
ordering = "AFTER"
side = "BOTH"
